"""empty message

Revision ID: 6bc218f66da7
Revises: c64c50084a4b
Create Date: 2018-06-13 23:17:02.794569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc218f66da7'
down_revision = 'c64c50084a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient', sa.String(length=140), nullable=True),
    sa.Column('ingredient_type', sa.String(length=140), nullable=True),
    sa.Column('quantity', sa.Float(precision=140), nullable=True),
    sa.Column('units', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_timestamp'), 'purchases', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchases_timestamp'), table_name='purchases')
    op.drop_table('purchases')
    # ### end Alembic commands ###
