"""empty message

Revision ID: d6cf2084b6f0
Revises: 5196177e1302
Create Date: 2018-06-28 00:25:37.320562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6cf2084b6f0'
down_revision = '5196177e1302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('binned', sa.Boolean(), nullable=True))
    op.add_column('purchases', sa.Column('binned_timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_purchases_binned_timestamp'), 'purchases', ['binned_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchases_binned_timestamp'), table_name='purchases')
    op.drop_column('purchases', 'binned_timestamp')
    op.drop_column('purchases', 'binned')
    # ### end Alembic commands ###
